sudo: required

language: python
python:
    - "3.5"
    - "3.6"

addons:
  mariadb: '10.1'

before_install:
    - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 8507EFA5
    - echo "deb http://repo.percona.com/apt `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install percona-toolkit

install:
    - pip install tox-travis

before_script:
    - sudo cp /etc/mysql/my.cnf /etc/my.cnf

script:
    - tox -e flake8
    - tox -e unit
